name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Format Check
        run: |
          make fmt

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download bin tools
        run: |
          make download-bin

      - name: Setup submodules
        run: |
          make submodules

      - name: Create python venv
        run: |
          make fprime-venv

      - name: Setup Zephyr
        run: |
          make zephyr-workspace

      - name: Setup Zephyr Export
        run: |
          make zephyr-export

      - name: Install Zephyr Python Dependencies
        run: |
          make zephyr-python-deps

      - name: Build
        run: |
          make build
